### ISSUE TITLE
add support to k8s contexts to use GPUs

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga-deployer#78]
```
---
kind: Job
apiVersion: batch/v1
metadata:
  name: job-test-gpu
  labels:
    name: job-test-gpu
spec:
  template:
    metadata:
      name: pod-test-gpu
      labels:
        name: pod-test-gpu
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest-gpu-py3
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        name: libcuda
      restartPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: svc-test-gpu
  labels:
    name: svc-test-gpu
spec:
  type: NodePort
  ports:
    - port: 8888
      name: nb
  selector:
    name: pod-test-gpu
```
